name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.2]
        dependency-stability: [prefer-stable]
    name: PHP ${{ matrix.php }} - ${{ matrix.dependency-stability }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, pest, pint
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run Pint (code style check)
        run: vendor/bin/pint --test

      - name: Run Pest tests
        run: vendor/bin/pest
